# params.yaml
IMAGE_SIZE: [224, 224, 3]
LEARNING_RATE: 0.0001
INCLUDE_TOP: False
WEIGHTS: "imagenet"
CLASSES: 5
ARTIFACTS_DIR: "artifacts"

EPOCHS: 50
BATCH_SIZE: 128
AUGMENTATION: True

MODEL_NAME: "MobileNetV2"

RESUME_TRAINING: True